server {
    listen 80;
    root /usr/share/nginx/html;

    # Gäste-Seite
    location = / {
        try_files /index.html =404;
    }

    # Lab Manager Dashboard
    location = /labmanager {
        try_files /labmanager.html =404;
    }

    # Statische Assets
    location / {
        try_files $uri =404;
    }

    gzip on;
    gzip_types text/html text/css application/javascript;
}
